services:
    database:
        image: postgres:${POSTGRES_VERSION}
        restart: always
        environment:
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
            TZ: ${TZ}
        volumes:
            - postgresql-data:/var/lib/postgresql/data

    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        depends_on:
            - database
        environment:
            APP_NAME: ${APP_NAME}
            APP_TIMEZONE: ${TZ}
            DB_CONNECTION: pgsql
            DB_HOST: database
            DB_PORT: ${POSTGRES_PORT}
            DB_DATABASE: ${DATABASE_NAME}
            DB_USERNAME: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./src/:/var/www/html/

    web:
        image: nginx:${NGINX_VERSION}
        ports:
            - 80:80
        depends_on:
            - app
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./src/:/var/www/html/

volumes:
    postgresql-data:
